describe("Test logic calculation", () => {
  it("Example with standard operations calculate successful", () => {
    cy.visit("/");
    cy.get("button").contains("2").click();
    cy.get("button").contains("*").click();
    cy.get("button").contains("2").click();
    cy.get("span").should("contain.text", "2*2");
    cy.get("button").contains("=").click();
    cy.get("span").should("contain.text", "4");
    cy.get("button").contains("2").click();
    cy.get("button").contains("/").click();
    cy.get("button").contains("2").click();
    cy.get("span").should("contain.text", "42/2");
    cy.get("button").contains("=").click();
    cy.get("span").should("contain.text", "21");
    cy.get("button").contains("+").click();
    cy.get("button").contains("2").click();
    cy.get("button").contains("1").click();
    cy.get("button").contains("0").click();
    cy.get("span").should("contain.text", "21+210");
    cy.get("button").contains("=").click();
    cy.get("span").should("contain.text", "231");
    cy.get("button").contains("-").click();
    cy.get("button").contains("1").click();
    cy.get("span").should("contain.text", "231-1");
    cy.get("button").contains("=").click();
    cy.get("span").should("contain.text", "230");
    cy.get("button").contains("(").click();
    cy.get("button").contains("1").click();
    cy.get("button").contains("/").click();
    cy.get("button").contains("2").click();
    cy.get("button").contains(")").click();
    cy.get("span").should("contain.text", "230(1/2)");
    cy.get("button").contains("=").click();
    cy.get("span").should("contain.text", "115");
    cy.get("button").contains(".").click();
    cy.get("button").contains("2").click();
    cy.get("button").contains("/").click();
    cy.get("button").contains("2").click();
    cy.get("span").should("contain.text", "115.2/2");
    cy.get("button").contains("=").click();
    cy.get("span").should("contain.text", "57.6");
    cy.get("button").contains("CE").click();
  });

  it("Example with multiply operations", () => {
    cy.get("button").contains("2").click();
    cy.get("button").contains("3").click();
    cy.get("button").contains("(").click();
    cy.get("button").contains("-").click();
    cy.get("button").contains("4").click();
    cy.get("button").contains("+").click();
    cy.get("button").contains("5").click();
    cy.get("button").contains("(").click();
    cy.get("button").contains("6").click();
    cy.get("button").contains("-").click();
    cy.get("button").contains("1").click();
    cy.get("button").contains(")").click();
    cy.get("button").contains("+").click();
    cy.get("button").contains("2").click();
    cy.get("span").should("contain.text", "23(-4+5(6-1)+2");
    cy.get("button").contains("=").click();
    cy.get("span").should("contain.text", "529");
  });
});
