describe("Test buttons", () => {
  it("Click buttons should update example", () => {
    cy.visit("/");
    cy.get("button").contains("0").click();
    cy.get("span").contains("0");
    cy.get("button").contains("1").click();
    cy.get("span").contains("1");
    cy.contains("2").click();
    cy.get("button").get("span").contains("2");
    cy.get("button").contains("3").click();
    cy.get("span").contains("3");
    cy.get("button").contains("4").click();
    cy.get("span").contains("4");
    cy.get("button").contains("5").click();
    cy.get("span").contains("5");
    cy.get("button").contains("6").click();
    cy.get("span").contains("6");
    cy.get("button").contains("/").click();
    cy.get("span").contains("/");
    cy.get("button").contains("7").click();
    cy.get("span").contains("7");
    cy.get("button").contains("*").click();
    cy.get("span").contains("*");
    cy.get("button").contains("8").click();
    cy.get("span").contains("8");
    cy.get("button").contains("-").click();
    cy.get("span").contains("-");
    cy.get("button").contains("9").click();
    cy.get("span").contains("9");
    cy.get("button").contains("+").click();
    cy.get("span").contains("+");
    cy.get("button").contains("(").click();
    cy.get("span").contains("(");
    cy.get("button").contains(")").click();
    cy.get("span").contains(")");
    cy.get("span").should("contain.text", "123456/7*8-9+()");
    cy.get("button").contains("C").click();
    cy.get("span").should("contain.text", "123456/7*8-9+(");
    cy.get("button").contains("CE").click();
    cy.get("span").should("contain.text", "0");
  });
});
